name: Run .NET Tests

on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: '9.0.x' # change to your version

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore --configuration Release

            - name: Run tests
              run: dotnet test --no-build --configuration Release --verbosity normal
